# Generated by Django 5.1.2 on 2024-12-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroComunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_centro_trabajo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('nombre_localidad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('nombre_turno', models.CharField(max_length=100)),
                ('nivel_educativo', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=255)),
                ('vacantes', models.IntegerField()),
            ],
        ),
    ]
