# Generated by Django 5.1.2 on 2024-12-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0002_centrocomunitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocomunitario',
            name='municipio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
