# Generated by Django 5.1.2 on 2025-01-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0003_centrocomunitario_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALC200_asignacion.centrocomunitario')),
                ('lec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALC200_asignacion.lec')),
            ],
        ),
    ]
