# Generated by Django 5.1.2 on 2025-01-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0004_asignacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignacion',
        ),
    ]
