# Generated by Django 5.1.2 on 2025-01-02 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0005_delete_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lec',
            name='centro_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ALC200_asignacion.centrocomunitario'),
        ),
    ]
