# Generated by Django 5.1.2 on 2025-01-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0007_lec_cct_centro_asignado_lec_estado_centro_asignado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lec',
            name='cct_centro_asignado',
        ),
    ]
