# Generated by Django 5.1.2 on 2025-01-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0008_remove_lec_cct_centro_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lec',
            name='cct_centro_asignado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
