# Generated by Django 5.1.2 on 2025-01-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0009_lec_cct_centro_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lec',
            name='cct_centro_asignado',
        ),
    ]
