# Generated by Django 5.1.2 on 2025-01-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0011_lec_cct_centro_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lec',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
