# Generated by Django 5.1.2 on 2025-01-05 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0012_lec_fecha_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lec',
            name='fecha_asignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALC200_asignacion.centrocomunitario')),
                ('lec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALC200_asignacion.lec')),
            ],
        ),
    ]
