# Generated by Django 5.1.2 on 2025-01-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0013_alter_lec_fecha_asignacion_historialasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lec',
            name='email',
            field=models.EmailField(default='hola@gmail.com', max_length=100),
        ),
    ]
