# Generated by Django 5.1.2 on 2025-01-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0014_lec_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lec',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
