# Generated by Django 5.1.2 on 2025-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0015_alter_lec_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lec',
            name='estado_aceptacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
