# Generated by Django 5.1.2 on 2025-01-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0017_lec_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lec',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='lec',
            name='estado_aceptacion',
            field=models.CharField(default='Aceptado', max_length=20),
        ),
    ]
