# Generated by Django 5.1.2 on 2025-01-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0012_remove_detallesusuario_estado_aprobacion_and_more'),
        ('ALC200_asignacion', '0018_remove_lec_usuario_alter_lec_estado_aceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lec',
            name='detalles_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ALC100_captacion.detallesusuario'),
        ),
    ]
