# Generated by Django 5.1.2 on 2025-01-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0019_lec_detalles_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lec',
            name='detalles_usuario',
        ),
    ]
