# Generated by Django 5.1.2 on 2025-01-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0022_remove_lec_detalles_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lec',
            name='id_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
