# Generated by Django 5.1.2 on 2025-01-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0023_lec_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocomunitario',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='centrocomunitario',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
