# Generated by Django 5.1.2 on 2025-01-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=40)),
                ('cantidad_disponible', models.IntegerField()),
                ('descripcion', models.CharField(max_length=360)),
                ('categoria', models.CharField(choices=[('Papelería', 'Papelería'), ('Utilería', 'Utilería'), ('Tecnología', 'Tecnología'), ('Mobiliario', 'Mobiliario')], max_length=18)),
            ],
        ),
    ]
