# Generated by Django 5.1.2 on 2025-01-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC200_asignacion', '0011_lec_cct_centro_asignado'),
        ('ALC600_logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.PositiveIntegerField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='ALC200_asignacion.centrocomunitario')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='ALC600_logistica.equipodisponible')),
            ],
        ),
    ]
