# Generated by Django 5.1.2 on 2025-01-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC600_logistica', '0002_asignacionmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipodisponible',
            name='categoria',
            field=models.CharField(choices=[('Papelería', 'Papelería'), ('Utilería', 'Utilería'), ('Mobiliario', 'Mobiliario')], max_length=18),
        ),
    ]
