# Generated by Django 5.1.2 on 2025-01-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC600_logistica', '0004_alter_equipodisponible_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentrosDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
