# Generated by Django 5.1.2 on 2025-01-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC600_logistica', '0005_centrosdistribucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipodisponible',
            name='volumen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
