# Generated by Django 5.1.2 on 2025-01-17 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ALC200_asignacion', '0023_lec_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sesiones', models.IntegerField()),
                ('modalidad', models.CharField(max_length=50)),
                ('fechas_sesiones', models.JSONField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALC200_asignacion.centrocomunitario')),
                ('lecs', models.ManyToManyField(to='ALC200_asignacion.lec')),
            ],
        ),
    ]
