# Generated by Django 5.1.2 on 2025-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC300_capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancapacitacion',
            name='asistencias',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='plancapacitacion',
            name='calificaciones',
            field=models.JSONField(default=dict),
        ),
    ]
