# Generated by Django 5.1.2 on 2025-01-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC300_capacitacion', '0002_plancapacitacion_asistencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancapacitacion',
            name='tipo_capacitacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
