# Generated by Django 5.1.2 on 2025-01-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC300_capacitacion', '0003_plancapacitacion_tipo_capacitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancapacitacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
