# Generated by Django 5.1.2 on 2025-01-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lec', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('grado', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('promedio_global', models.DecimalField(decimal_places=2, max_digits=4)),
                ('centro_educativo', models.CharField(max_length=100)),
                ('procedencia', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
    ]
