# Generated by Django 5.1.2 on 2025-01-11 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nivel_educativo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grado', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('bimestre', models.IntegerField()),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALC500_control_escolar.estudiante')),
            ],
        ),
    ]
