# Generated by Django 5.1.2 on 2025-01-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0002_estudiante_nivel_educativo_calificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido_materno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido_paterno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
