# Generated by Django 5.1.2 on 2025-01-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0003_estudiante_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
