# Generated by Django 5.1.2 on 2025-01-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0004_calificaciones_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_inscripcion_centro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
