# Generated by Django 5.1.2 on 2025-01-13 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0005_estudiante_fecha_inscripcion_centro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_inscripcion_centro',
        ),
        migrations.CreateModel(
            name='HistorialMigratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('clave_centro_trabajo', models.CharField(max_length=15)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALC500_control_escolar.estudiante')),
            ],
        ),
    ]
