# Generated by Django 5.1.2 on 2025-01-14 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0006_remove_estudiante_fecha_inscripcion_centro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('nuevo_nivel_educativo', models.CharField(max_length=100)),
                ('nuevo_grado', models.CharField(max_length=50)),
                ('nuevo_grupo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALC500_control_escolar.estudiante')),
            ],
        ),
    ]
