# Generated by Django 5.1.2 on 2025-01-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0007_reinscripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reinscripcion',
        ),
    ]
