# Generated by Django 5.1.2 on 2025-01-14 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0009_reinscripcionestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinscripcionestudiante',
            name='id_estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ALC500_control_escolar.estudiante'),
            preserve_default=False,
        ),
    ]
