# Generated by Django 5.1.2 on 2025-01-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0010_reinscripcionestudiante_id_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinscripcionestudiante',
            name='id_estudiante',
            field=models.IntegerField(),
        ),
    ]
