# Generated by Django 5.1.2 on 2025-01-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALC500_control_escolar', '0011_alter_reinscripcionestudiante_id_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinscripcionestudiante',
            name='id_estudiante',
        ),
    ]
