# Generated by Django 5.1.2 on 2024-11-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALC000_sistema_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
