# Generated by Django 5.1.2 on 2025-01-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC000_sistema_base', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='esta_asignado',
            field=models.BooleanField(default=False),
        ),
    ]
