# Generated by Django 5.1.2 on 2025-01-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC000_sistema_base', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('aspirante_lec', 'Aspirante a Líder para la Educación Comunitaria'), ('coord_nac_rrhh', 'Coordinador Nacional de Recursos Humanos'), ('lider_lec', 'Líder para la Educación Comunitaria'), ('coord_academico', 'Coordinador Académico'), ('aux_operacion', 'Auxiliar de Operación'), ('coord_nac_logistica', 'Coordinador Nacional de Apoyo y Logística'), ('coord_operativo', 'Coordinador Operativo'), ('dep_finanzas', 'Departamento de Finanzas')], default='aspirante_lec', max_length=20),
        ),
    ]
