# Generated by Django 5.1.3 on 2024-11-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_convocatoria', models.CharField(max_length=50)),
                ('fecha_limite_registro', models.DateField()),
                ('fecha_entrega_resultados', models.DateField()),
                ('max_participantes', models.PositiveIntegerField()),
            ],
        ),
    ]
