# Generated by Django 5.1.2 on 2024-11-22 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_convocatoria', models.CharField(max_length=50)),
                ('fecha_limite_registro', models.DateField()),
                ('fecha_entrega_resultados', models.DateField()),
                ('max_participantes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('talla_playera', models.CharField(max_length=5)),
                ('talla_pantalon', models.CharField(max_length=5)),
                ('talla_calzado', models.CharField(max_length=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('banco', models.CharField(choices=[('BBVA', 'BBVA'), ('Banamex', 'Banamex'), ('Santander', 'Santander'), ('HSBC', 'HSBC'), ('Banorte', 'Banorte'), ('Scotiabank', 'Scotiabank'), ('Inbursa', 'Inbursa'), ('Banco Azteca', 'Banco Azteca'), ('BanCoppel', 'BanCoppel'), ('Banco del Bajío', 'Banco del Bajío')], max_length=50)),
                ('nivel_estudios', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Licenciatura', 'Licenciatura')], max_length=50)),
                ('nivel_estudios_deseado', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Licenciatura', 'Licenciatura')], max_length=50)),
                ('experiencia_ciencia', models.CharField(choices=[('Biologia', 'Biología'), ('Fisica', 'Física'), ('Quimica', 'Química'), ('Otro', 'Otro'), ('Ninugna', 'Ninguna')], max_length=50)),
                ('experiencia_arte', models.CharField(choices=[('Musica', 'Música'), ('Teatro', 'Teatro'), ('Artes Plasticas', 'Artes Plásticas'), ('Literatura', 'Literatura'), ('Ninguna', 'Ninguna')], max_length=50)),
                ('interes_desarrollo_comunitario', models.BooleanField()),
                ('razones_interes', models.CharField(choices=[('Recibir apoyo económico para continuar estudios', 'Recibir apoyo económico'), ('Tener experiencia como líder en educación comunitaria y compartir conocimientos', 'Experiencia como líder'), ('No perder el año y realizar alguna actividad', 'No perder el año'), ('Conocer personas y trabajar con niños', 'Conocer personas'), ('Apoyar y participar en programas sociales', 'Apoyar en programas sociales')], max_length=50)),
                ('profesion_interes', models.CharField(max_length=50)),
                ('interes_incorporacion', models.CharField(choices=[('Prácticas profesionales', 'Prácticas profesionales'), ('Servicio social', 'Servicio social'), ('Residencia profesional', 'Residencia profesional'), ('Movilidad académica', 'Movilidad académica'), ('Participación voluntaria', 'Participación voluntaria')], max_length=50)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('CDMX', 'CDMX'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Mexico', 'México'), ('Michoacan', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatan', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('numero_interior', models.CharField(blank=True, max_length=10)),
                ('estado_deseado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('CDMX', 'CDMX'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Mexico', 'México'), ('Michoacan', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatan', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=50)),
                ('municipio_deseado', models.CharField(max_length=50)),
                ('certificado', models.CharField(blank=True, max_length=50)),
                ('identificacion', models.CharField(blank=True, max_length=50)),
                ('estado_cuenta', models.CharField(blank=True, max_length=50)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
