# Generated by Django 5.1.2 on 2024-11-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesusuario',
            name='razones_interes',
            field=models.CharField(choices=[('Recibir apoyo económico para continuar estudios', 'Recibir apoyo económico'), ('Tener experiencia como líder en educación comunitaria y compartir conocimientos', 'Experiencia como líder'), ('No perder el año y realizar alguna actividad', 'No perder el año'), ('Conocer personas y trabajar con niños', 'Conocer personas'), ('Apoyar y participar en programas sociales', 'Apoyar en programas sociales')], max_length=100),
        ),
    ]
