# Generated by Django 5.1.2 on 2024-12-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0002_alter_detallesusuario_razones_interes_inscripciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesusuario',
            name='clabe',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='banco',
            field=models.CharField(choices=[('BBVA', 'BBVA'), ('Banamex', 'Banamex'), ('Santander', 'Santander'), ('HSBC', 'HSBC'), ('Banorte', 'Banorte'), ('Scotiabank', 'Scotiabank'), ('Inbursa', 'Inbursa'), ('Banco Azteca', 'Banco Azteca'), ('BanCoppel', 'BanCoppel'), ('Banco del Bajío', 'Banco del Bajío'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
