# Generated by Django 5.1.2 on 2024-12-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0003_detallesusuario_clabe_alter_detallesusuario_banco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesusuario',
            name='nacionalidad',
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='profesion_interes',
            field=models.CharField(choices=[('Ingeniería', 'Ingeniería'), ('Ciencias de la Salud', 'Ciencias de la Salud'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Ciencias Exactas', 'Ciencias Exactas'), ('Ciencias Naturales', 'Ciencias Naturales'), ('Artes', 'Artes'), ('Humanidades', 'Humanidades'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
