# Generated by Django 5.1.2 on 2024-12-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0002_alter_detallesusuario_razones_interes'),
        ('ALC100_captacion', '0004_remove_detallesusuario_nacionalidad_and_more'),
    ]

    operations = [
    ]
