# Generated by Django 5.1.2 on 2024-12-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0005_merge_20241204_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesusuario',
            name='estado_deseado',
        ),
        migrations.AddField(
            model_name='detallesusuario',
            name='afecciones',
            field=models.CharField(choices=[('Diabetes', 'Diabetes'), ('Hipertension', 'Hipertension'), ('Asma', 'Asma'), ('Otro', 'Otro'), ('Ninguna', 'Ninguna')], default='Ninguna', max_length=15),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='experiencia_ciencia',
            field=models.CharField(choices=[('Biologia', 'Biología'), ('Fisica', 'Física'), ('Quimica', 'Química'), ('Otro', 'Otro'), ('Ninguna', 'Ninguna')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='localidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='nivel_estudios',
            field=models.CharField(choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='nivel_estudios_deseado',
            field=models.CharField(choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='talla_pantalon',
            field=models.CharField(choices=[('CH', 'Chica'), ('M', 'Mediana'), ('G', 'Grande'), ('EG', 'Extra Grande')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='talla_playera',
            field=models.CharField(choices=[('CH', 'Chica'), ('M', 'Mediana'), ('G', 'Grande'), ('EG', 'Extra Grande')], max_length=2),
        ),
    ]
