# Generated by Django 5.1.2 on 2024-12-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0007_remove_detallesusuario_municipio_deseado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesusuario',
            name='certificado',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='estado_cuenta',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='detallesusuario',
            name='identificacion',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
