# Generated by Django 5.1.2 on 2024-12-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0008_alter_detallesusuario_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesusuario',
            name='aprobacion',
            field=models.BooleanField(default=False),
        ),
    ]
