# Generated by Django 5.1.2 on 2025-01-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0008_alter_detallesusuario_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesusuario',
            name='estado_aceptacion',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10),
        ),
    ]
