# Generated by Django 5.1.2 on 2025-01-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0009_detallesusuario_aprobacion'),
        ('ALC100_captacion', '0009_detallesusuario_estado_aceptacion'),
    ]

    operations = [
    ]
