# Generated by Django 5.1.2 on 2025-01-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0010_merge_20250105_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesusuario',
            name='aprobacion',
        ),
        migrations.AddField(
            model_name='detallesusuario',
            name='estado_aprobacion',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10),
        ),
    ]
