# Generated by Django 5.1.2 on 2025-01-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC400_apoyos_economicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoapoyo',
            name='confirmacion_lec',
            field=models.CharField(blank=True, choices=[('recibido', 'Recibido'), ('error', 'Error'), ('no_recibido', 'No Recibido')], max_length=20, null=True),
        ),
    ]
