# Generated by Django 5.1.2 on 2025-01-07 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC400_apoyos_economicos', '0002_pagoapoyo_confirmacion_lec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ALC004TiposBecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ALC401LecBecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.IntegerField(default=0)),
                ('tipo_beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='ALC400_apoyos_economicos.alc004tiposbecas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
