# Generated by Django 5.1.2 on 2025-01-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC400_apoyos_economicos', '0003_alc004tiposbecas_alc401lecbecas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoapoyo',
            name='concepto',
            field=models.CharField(choices=[('Beca', 'Beca'), ('Seguimiento', 'Seguimiento'), ('Continuacion', 'Continuacion'), ('Apoyo Mensual de Servicio', 'Apoyo Mensual de Servicio'), ('Beca de Continuidad 30 Meses', 'Beca de Continuidad 30 Meses'), ('Beca de Continuidad 60 Meses', 'Beca de Continuidad 60 Meses')], max_length=50),
        ),
    ]
