# Generated by Django 5.1.2 on 2025-01-19 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALC100_captacion', '0012_remove_detallesusuario_estado_aprobacion_and_more'),
        ('ALC400_apoyos_economicos', '0004_alter_pagoapoyo_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoapoyo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ALC100_captacion.detallesusuario'),
        ),
    ]
